#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt-get update -y -qq
sudo apt-get install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bckp
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

sudo service nginx restart

sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.example.com/new_page;\n\t}' /etc/nginx/sites-available/default
sudo service nginx reload
