#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx

echo 'add_header X-Served-By $HOSTNAME;' | sudo tee -a /etc/nginx/sites-available/default

sudo systemctl restart nginx
