#!/usr/bin/env bash
# Displays 'Best School' 10 times, but at 9th iteration,
# displays 'Best School' then 'Hi' on a new line, using while loop and if

counter=0

while [ $counter -lt 10 ]
do
	echo "Best School"
	if [ $counter -eq 8 ]
	then
		echo "Hi"
	fi
	(( counter++ ))
done
