#!/usr/bin/env bash
# Iterate a number 10 times from 0
# Displays a text at each iteration
# Displays something else at 4th and 8th iteration

counter=0

while [ $counter -lt 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( counter++ ))
done
